### ISSUE TITLE
ptz error

### ISSUE THREAD

**Issue by sobhaniot** [Gowresh7/V380_Python#3]
hi i use your code for v380 camera. it's work but when i want move camera to left or right or up, down, that move to end of possible it can. why? how i can use this xml code for movement step by step and slowly?

**Comment by Arvinth-Krishna** [comment]
any update on this?

**rtsp://admin:c123*556@192.168.2.108:554/live/ch00_0** this is RTPS URL for my V380 camera and so i tried to control my camera movement with this URL and it not working **http://admin:c123*556@192.168.2.108:8899/onvif/ptz**

please help how to control the camera - I tried ur V380post.py script.

```
Enter a command (i for up, , for down, j for left, l for right, k to stop, q to quit): i
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\DELL\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Roaming\Python\Python311\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
